"""Binary framing: uint32 (big-endian) header length | JSON header | blobs.

Blob payloads follow the header back-to-back in the order listed in
`header.blobs`. Numpy arrays travel raw (dtype + shape in the BlobSpec);
images may travel jpeg/png-encoded. The C# MessageCodec implements exactly
this layout and is validated against golden fixture files generated by
tests/unit/test_protocol.py.
"""

from __future__ import annotations

import json
import struct
from typing import Any

import cv2
import numpy as np

from dronecv.protocol.messages import AnyMessage, BlobSpec, parse_message

MAX_HEADER_LEN = 1 << 20  # 1 MiB of JSON is already pathological
MAX_BLOB_LEN = 1 << 28  # 256 MiB


class ProtocolError(RuntimeError):
    pass


def encode_blob(name: str, value: np.ndarray | bytes, encoding: str = "raw", jpeg_quality: int = 92) -> tuple[BlobSpec, bytes]:
    """Serialize one blob and produce its spec."""
    if isinstance(value, bytes):
        return BlobSpec(name=name, dtype="bytes", shape=None, encoding=encoding, byte_len=len(value)), value

    arr = np.ascontiguousarray(value)
    if encoding == "raw":
        if arr.dtype == np.uint8:
            dtype = "uint8"
        elif arr.dtype == np.float32:
            dtype = "float32"
        else:
            raise ProtocolError(f"unsupported raw blob dtype {arr.dtype}")
        data = arr.tobytes()
        return BlobSpec(name=name, dtype=dtype, shape=list(arr.shape), encoding="raw", byte_len=len(data)), data

    if encoding in ("jpeg", "png"):
        if arr.dtype != np.uint8:
            raise ProtocolError(f"{encoding} blobs must be uint8 images")
        ext = ".jpg" if encoding == "jpeg" else ".png"
        params = [cv2.IMWRITE_JPEG_QUALITY, jpeg_quality] if encoding == "jpeg" else []
        # cv2 expects BGR; we standardize on RGB in memory and swap at the codec.
        bgr = cv2.cvtColor(arr, cv2.COLOR_RGB2BGR) if arr.ndim == 3 else arr
        ok, buf = cv2.imencode(ext, bgr, params)
        if not ok:
            raise ProtocolError(f"failed to {encoding}-encode blob '{name}'")
        data = buf.tobytes()
        return BlobSpec(name=name, dtype="uint8", shape=list(arr.shape), encoding=encoding, byte_len=len(data)), data

    raise ProtocolError(f"unknown blob encoding '{encoding}'")


def decode_blob(spec: BlobSpec, data: bytes) -> np.ndarray | bytes:
    if spec.encoding == "raw":
        if spec.dtype == "bytes" or spec.shape is None:
            return data
        arr = np.frombuffer(data, dtype=spec.dtype)
        return arr.reshape(spec.shape).copy()
    if spec.encoding in ("jpeg", "png"):
        buf = np.frombuffer(data, dtype=np.uint8)
        img = cv2.imdecode(buf, cv2.IMREAD_UNCHANGED)
        if img is None:
            raise ProtocolError(f"failed to decode {spec.encoding} blob '{spec.name}'")
        if img.ndim == 3:
            img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        return img
    raise ProtocolError(f"unknown blob encoding '{spec.encoding}'")


def encode_message(
    msg: AnyMessage,
    blobs: dict[str, tuple[np.ndarray | bytes, str]] | None = None,
    jpeg_quality: int = 92,
) -> bytes:
    """`blobs` maps name -> (value, encoding). Specs are written into the header."""
    specs: list[BlobSpec] = []
    payloads: list[bytes] = []
    for name, (value, encoding) in (blobs or {}).items():
        spec, data = encode_blob(name, value, encoding, jpeg_quality)
        specs.append(spec)
        payloads.append(data)
    header_dict: dict[str, Any] = msg.model_dump(mode="json")
    header_dict["blobs"] = [s.model_dump(mode="json") for s in specs]
    header_bytes = json.dumps(header_dict, separators=(",", ":"), sort_keys=True).encode("utf-8")
    if len(header_bytes) > MAX_HEADER_LEN:
        raise ProtocolError("header too large")
    return struct.pack(">I", len(header_bytes)) + header_bytes + b"".join(payloads)


def decode_message(data: bytes) -> tuple[AnyMessage, dict[str, np.ndarray | bytes]]:
    """Decode one complete frame from a bytes buffer (for tests/fixtures)."""
    if len(data) < 4:
        raise ProtocolError("truncated frame")
    (header_len,) = struct.unpack(">I", data[:4])
    header = json.loads(data[4 : 4 + header_len].decode("utf-8"))
    msg = parse_message(header)
    blobs: dict[str, np.ndarray | bytes] = {}
    off = 4 + header_len
    for spec in msg.blobs:
        blobs[spec.name] = decode_blob(spec, data[off : off + spec.byte_len])
        off += spec.byte_len
    return msg, blobs
