// Locates the cross-language fixture files. They are generated by
// scripts/gen_protocol_fixtures.py, which copies them into this package's
// Tests/Fixtures directory — run it (and commit) after any protocol change.

using System.IO;
using NUnit.Framework;

namespace DroneCV.Flight.Tests
{
    public static class FixturePaths
    {
        public static string Root
        {
            get
            {
                // Package location relative to the Unity project varies; walk
                // up from this source file's known package layout.
                var candidates = new[]
                {
                    Path.Combine("Packages", "com.dronecv.flight", "Tests", "Fixtures"),
                    Path.Combine("..", "unity", "com.dronecv.flight", "Tests", "Fixtures"),
                };
                foreach (var c in candidates)
                    if (Directory.Exists(c)) return c;
                Assert.Ignore("fixture directory not found — run scripts/gen_protocol_fixtures.py and reimport");
                return null;
            }
        }

        public static string File(string name) => Path.Combine(Root, name);
    }
}
