// Binary framing for the dronecv protocol:
//   uint32 (big-endian) header length | JSON header (utf-8) | blob payloads
// Mirror of src/dronecv/protocol/framing.py. Validated against the golden
// fixture files generated by scripts/gen_protocol_fixtures.py (see
// Tests/CodecGoldenTests.cs) — if those tests fail, the two codecs diverged.

using System;
using System.Collections.Generic;
using System.IO;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace DroneCV.Flight.Protocol
{
    public class Blob
    {
        public BlobSpec Spec;
        public byte[] Data;
    }

    public class DecodedMessage
    {
        public string Type;
        public JObject Raw;               // full header for typed re-parse
        public Dictionary<string, Blob> Blobs = new Dictionary<string, Blob>();

        public T As<T>() where T : Header
        {
            return Raw.ToObject<T>(MessageCodec.Serializer);
        }
    }

    public static class MessageCodec
    {
        public static readonly JsonSerializer Serializer = new JsonSerializer
        {
            NullValueHandling = NullValueHandling.Ignore,
        };

        // ------------------------------------------------------------ encode

        public static byte[] Encode(Header msg, List<Blob> blobs = null)
        {
            msg.Blobs = new List<BlobSpec>();
            if (blobs != null)
            {
                foreach (var b in blobs)
                {
                    b.Spec.ByteLen = b.Data.LongLength;
                    msg.Blobs.Add(b.Spec);
                }
            }
            // Compact, sorted-keys JSON mirrors the Python encoder closely
            // enough (the decoder on either side never relies on key order).
            var jo = JObject.FromObject(msg, SerializerWithNulls());
            var headerJson = jo.ToString(Formatting.None);
            var headerBytes = System.Text.Encoding.UTF8.GetBytes(headerJson);
            if (headerBytes.Length > ProtocolConstants.MaxHeaderLen)
                throw new InvalidDataException("header too large");

            using (var ms = new MemoryStream())
            {
                WriteUInt32BE(ms, (uint)headerBytes.Length);
                ms.Write(headerBytes, 0, headerBytes.Length);
                if (blobs != null)
                    foreach (var b in blobs)
                        ms.Write(b.Data, 0, b.Data.Length);
                return ms.ToArray();
            }
        }

        private static JsonSerializer SerializerWithNulls()
        {
            // Fields annotated with NullValueHandling.Include keep explicit
            // nulls (the Python schema uses null for optional values).
            return new JsonSerializer { NullValueHandling = NullValueHandling.Ignore };
        }

        // ------------------------------------------------------------ decode

        public static DecodedMessage Decode(Stream stream)
        {
            var lenBuf = ReadExactly(stream, 4);
            var headerLen = (uint)((lenBuf[0] << 24) | (lenBuf[1] << 16) | (lenBuf[2] << 8) | lenBuf[3]);
            if (headerLen > ProtocolConstants.MaxHeaderLen)
                throw new InvalidDataException($"header length {headerLen} exceeds limit");
            var headerBytes = ReadExactly(stream, (int)headerLen);
            var jo = JObject.Parse(System.Text.Encoding.UTF8.GetString(headerBytes));

            var decoded = new DecodedMessage
            {
                Type = (string)jo["type"],
                Raw = jo,
            };
            var specs = jo["blobs"]?.ToObject<List<BlobSpec>>(Serializer) ?? new List<BlobSpec>();
            foreach (var spec in specs)
            {
                if (spec.ByteLen > ProtocolConstants.MaxBlobLen)
                    throw new InvalidDataException($"blob '{spec.Name}' too large");
                decoded.Blobs[spec.Name] = new Blob
                {
                    Spec = spec,
                    Data = ReadExactly(stream, (int)spec.ByteLen),
                };
            }
            return decoded;
        }

        public static DecodedMessage DecodeBytes(byte[] data)
        {
            using (var ms = new MemoryStream(data))
                return Decode(ms);
        }

        // ------------------------------------------------------------ helpers

        public static Blob RawFloat32Blob(string name, float[] values, int[] shape)
        {
            var data = new byte[values.Length * 4];
            Buffer.BlockCopy(values, 0, data, 0, data.Length);
            return new Blob
            {
                Spec = new BlobSpec { Name = name, Dtype = "float32", Shape = shape, Encoding = "raw" },
                Data = data,
            };
        }

        public static Blob EncodedImageBlob(string name, byte[] encoded, string encoding, int height, int width)
        {
            return new Blob
            {
                Spec = new BlobSpec
                {
                    Name = name,
                    Dtype = "uint8",
                    Shape = new[] { height, width, 3 },
                    Encoding = encoding,
                },
                Data = encoded,
            };
        }

        private static void WriteUInt32BE(Stream s, uint v)
        {
            s.WriteByte((byte)(v >> 24));
            s.WriteByte((byte)(v >> 16));
            s.WriteByte((byte)(v >> 8));
            s.WriteByte((byte)v);
        }

        private static byte[] ReadExactly(Stream s, int n)
        {
            var buf = new byte[n];
            var off = 0;
            while (off < n)
            {
                var read = s.Read(buf, off, n - off);
                if (read <= 0) throw new EndOfStreamException();
                off += read;
            }
            return buf;
        }
    }
}
